---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-backend-cfg
data:
  TOWER_REDIS_URL: "redis://${TOWER_REDIS_HOSTNAME}:6379"
  TOWER_DB_URL: "jdbc:mysql://${TOWER_DB_HOSTNAME}:3306/${TOWER_DB_SCHEMA}?&usePipelineAuth=false&useBatchMultiSend=false&allowPublicKeyRetrieval=true&useSSL=false"
  TOWER_DB_PASSWORD: "${TOWER_DB_PASSWORD}"
...
